version: '3.3'

services:
  vdalen-configservice:
    build:
      context: ./config-service/target/docker-files
      dockerfile: Dockerfile
    container_name: vdalen-configservice
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./config-service/config:/data
    environment:
      SPRING_PROFILES_ACTIVE: "native"

  vdalen-discoveryservice:
    build:
      context: ./discovery-service/target/docker-files
      dockerfile: Dockerfile
    container_name: vdalen-discoveryservice
    restart: unless-stopped
    ports:
      - 8761:8761
    links:
      - vdalen-configservice
    depends_on:
      - vdalen-configservice
    environment:
      SPRING_PROFILES_ACTIVE: "native"
      CONFIGSERVICE_INSTANCE_HOST: "vdalen-configservice"
