version: '3.3'

services:
  configservice:
    build:
      context: ./config-service/target/docker-files
      dockerfile: Dockerfile
    container_name: configservice
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./config-service/config:/data
    environment:
      SPRING_PROFILES_ACTIVE: "native"

  discoveryservice:
    build:
      context: ./discovery-service/target/docker-files
      dockerfile: Dockerfile
    container_name: discoveryservice
    restart: unless-stopped
    ports:
      - 8761:8761
    links:
      - configservice
    depends_on:
      - configservice
    environment:
      SPRING_PROFILES_ACTIVE: "native"
      CONFIGSERVICE_INSTANCE_HOST: "configservice"
