version: '3.3'

services:
  vdalen-config-service:
    build:
      context: ./config-service/target/docker-files
      dockerfile: Dockerfile
    container_name: vdalen-config-service
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./config-service/config:/data
    environment:
      spring.profiles.active: native

  vdalen-discovery-service:
    build:
      context: ./discovery-service/target/docker-files
      dockerfile: Dockerfile
    container_name: vdalen-discoveryservice-service
    restart: unless-stopped
    ports:
      - 8761:8761
    links:
      - vdalen-config-service
    depends_on:
      - vdalen-config-service
    environment:
      spring.profiles.active: native
      spring.cloud.config.uri: http://vdalen-config-service:8888
