server:
  port: 8761

eureka:
  name: Discovery Service
  datacenter: Vdalen
  client:
    region: eu-central-1
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
