eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

crux:
  configurationRoot: data/
  schedule:
    pipeline: "*/3 * * * * ?"
    uimaAnnotator: "*/3 * * * * ?"
    jenaVelocitySerializer: "*/3 * * * * ?"

logging:
  level:
    ROOT: ERROR

    com.netflix.hystrix: INFO

    org.apache.http.impl.execchain.RetryExec: ERROR

    com.wolterskluwer.crux: INFO
    com.wolterskluwer.crux.model: ERROR
    com.wolterskluwer.crux.config: ERROR
    com.wolterskluwer.crux.core: INFO
    com.wolterskluwer.crux.service: INFO
    com.wolterskluwer.crux.web: INFO
