spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

crux:
  configurationRoot: ../data/
  schedule:
    pipeline: "*/3 * * * * ?"
    uimaAnnotator: "*/3 * * * * ?"
    jenaVelocitySerializer: "*/3 * * * * ?"
    decoratedElements: "*/3 * * * * ?"
  security:
    users:
      # Passwords are Bcrypt encoded
      - username: "user"
        password: "{bcrypt}$2a$10$Qd6qttIjuPEGA41EbRdLS.Hphg/1j5VhiLHiTXoQXOaxPw95NNNfG" #-> cruxuser
      - username: "admin"
        password: "{bcrypt}$2a$10$E7Yk6zukR6DJqYNc0nhO6u5HpCdHnmVhfQRkHVlpBaYC5.CKfE0M2" #-> cruxadmin
        roles:
          - ADMIN
          - MONITORING

server:
  tomcat:
    max-threads: 1024
    accept-count: 1024
    max-http-post-size: 10485760 # 10MB
  servlet:
    context-path: /crux
  error:
    path: /error

management:
  server:
    servlet:
      context-path: /crux/admin
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
  health:
    diskspace:
      enabled: true
      threshold: 1B

hystrix:
  # Configuration options: https://github.com/Netflix/Hystrix/wiki/Configuration
  threadpool:
    default:
      # This property allows the configuration for maximumSize to take effect.
      allowMaximumSizeToDivergeFromCoreSize: true
      # This property sets the core thread-pool size.
      coreSize: 10
      # This is the maximum amount of concurrency that can be supported without starting to reject HystrixCommands
      maximumSize: 128
      # This property sets the maximum queue size of the BlockingQueue implementation. If you set this to -1 then SynchronousQueue will be used, otherwise a positive value will be used with LinkedBlockingQueue.
      # This property only applies at initialization time since queue implementations cannot be resized or changed without re-initializing the thread executor which is not supported.
      maxQueueSize: -1
      # his property sets the queue size rejection threshold — an artificial maximum queue size at which rejections will occur even if maxQueueSize has not been reached. This property exists because the maxQueueSize of a BlockingQueue cannot be dynamically changed and we want to allow you to dynamically change the queue size that affects rejections.
      queueSizeRejectionThreshold: 120
  command:
    default:
      execution:
        isolation:
          # THREAD:    Execute the {@link HystrixCommand#run()} method on a separate thread and restrict concurrent executions using the thread-pool size.
          # SEMAPHORE: Execute the {@link HystrixCommand#run()} method on the calling thread and restrict concurrent executions using the semaphore permit count.
          strategy: THREAD
          thread:
            # The time in milliseconds after which the caller will observe a timeout and walk away from the command execution
            # 600000ms => 600s => 10 minutes
            timeoutInMilliseconds: 600000

logging:
  level:
    ROOT: ERROR

    com.netflix.hystrix: ERROR

    org.apache.http.impl.execchain.RetryExec: DEBUG

    com.wolterskluwer.crux: INFO
    com.wolterskluwer.crux.model: ERROR
    com.wolterskluwer.crux.config: ERROR
    com.wolterskluwer.crux.core: DEBUG
    com.wolterskluwer.crux.service: DEBUG
    com.wolterskluwer.crux.web: DEBUG

    org.apache.uima.ruta: ERROR
    org.apache.jena: ERROR
    com.hp.hpl.jena: ERROR
